- name: Copy our executable script to remote location, execute script.
  remote_user: root
  hosts: Install
  tasks:
     - name: Transfer executable script script
       copy: src=./docker-awcli-jenkins.sh dest=/home/ubuntu mode=755
     - name: Execute the script
       command: /home/ubuntu/docker-awcli-jenkins.sh